### ISSUE TITLE
Crashes homebridge when activating a “button” that doesn’t exist in Bond

### ISSUE THREAD

**Issue by raygan** [aarons22/homebridge-bond#10]
I have my fans connected to smart switches for on/off and only use Bond for speed control, so I don’t have the Power button from my remote added to Bond. (That helps keep me from having situations whe the fan is on at the Switch but off on the remote.)

When I use the plugin it crashes homebridge any time the Bond fan state changes to Off. Here’s what I see in the log:

```
usr/local/lib/node_modules/homebridge-bond/dist/bond.js:66
        let url = "https://" + this.id + ".local:4433/api/v1/device/" + (parseInt(device.propertyId) - 1) + "/device_property/" + device.propertyId + "/device_property_command/" + command.propertyId + "/run";
                                                                                                                                                                                            ^

TypeError: Cannot read property 'propertyId' of undefined
    at Bond.sendCommand (/usr/local/lib/node_modules/homebridge-bond/dist/bond.js:66:189)
    at Characteristic.<anonymous> (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:167:22)
    at emitMany (events.js:147:13)
    at Characteristic.emit (events.js:224:7)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:320:10)
    at Bridge.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:871:22)
    at Array.forEach (<anonymous>)
    at Bridge.Accessory._handleSetCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:811:8)
    at emitMany (events.js:147:13)
    at HAPServer.emit (events.js:224:7)
    at HAPServer._handleCharacteristics (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:972:10)
    at HAPServer.<anonymous> (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:209:39)
    at emitNone (events.js:106:13)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by plainsane** [comment]
I’ll see if I can take a look in a couple of days

**Comment by aarons22** [comment]
Closing this as it is no longer applicable with v2 API.
