### ISSUE TITLE
cannot read property 'bondid'

### ISSUE THREAD

**Issue by dhpeter** [aarons22/homebridge-bond#134]
This issue just started happening. I haven't touched anything except upgrade the version.

It starts with:

A request error occured: undefined
Error getting version: TypeError: Cannot read property 'bondid' of undefined

Error getting device ids: TypeError: cannot convert undefined or null object

and crashes homebridge. Confirmed token and ip have not changed

**Comment by mathewsears** [comment]
I’m getting the same messages. Did you ever come up with a solution?

**Comment by dhpeter** [comment]
Negative. I’ve removed bond for now.

**Comment by mathewsears** [comment]
Not sure of your setup. I run of a PI running Raspbian.  I ran commands to update my installed packages.  After doing this and rebooting, my BOND ceiling fans showed back up in homebridge.

sudo apt-get update
sudo apt-get dist-upgrade

**Comment by aarons22** [comment]
what was the previous version you were on? can you post your homebridge config?

**Comment by dhpeter** [comment]
Bond plugin version: 3.2.3

Here’s my bond snippet.

 

{

            "platform": "Bond",

            "bonds": [

                {

                    "ip_address": "192.168.68.136",

                    "token": "e5d94********"

                }

            ]

        }

**Comment by sundar2012** [comment]
I have been getting the same issue.  Oddly, it persists after restarting the Rodman container that home bridge  (podman restart homebridge) runs in - but does not persist when I restart the hardware im running the container in (UDM Pro).  It ultimately creates a boot loop in the container for homebridge.

`[5/25/2021, 11:43:14 AM] Homebridge v1.3.4 (Homebridge 0CB5) is running on port 51655.
[5/25/2021, 11:43:24 AM] [Bond] A request error occurred: undefined
[5/25/2021, 11:43:24 AM] [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
[5/25/2021, 11:43:24 AM] [Bond] A request error occurred: undefined
[5/25/2021, 11:43:24 AM] [Bond] Error getting version: TypeError: Cannot read property 'bondid' of undefined
[5/25/2021, 11:43:24 AM] [Bond] 6 cached accessories were loaded
(node:415) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bondid' of undefined
    at BondPlatform.getDevices (/homebridge/node_modules/homebridge-bond/dist/platform.js:47:65)
    at /homebridge/node_modules/homebridge-bond/dist/platform.js:39:26
    at Array.forEach (<anonymous>)
    at /homebridge/node_modules/homebridge-bond/dist/platform.js:38:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at runNextTicks (internal/process/task_queues.js:64:3)
    at processTimers (internal/timers.js:495:9)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:415) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:415) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[5/25/2021, 11:43:25 AM] [Bond] Configuring Accessory: Patio Fan
[5/25/2021, 11:43:25 AM] TypeError: Cannot read property 'bondid' of undefined
    at /homebridge/node_modules/homebridge-bond/dist/platform.js:207:57
    at Array.find (<anonymous>)
    at BondPlatform.bondForDevice (/homebridge/node_modules/homebridge-bond/dist/platform.js:207:37)
    at BondPlatform.create (/homebridge/node_modules/homebridge-bond/dist/platform.js:163:27)
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-bond/dist/platform.js:155:26)
    at listOnTimeout (internal/timers.js:555:17)
    at processTimers (internal/timers.js:498:7)`

**Comment by aarons22** [comment]
Hey all - I've got some better logging coming to help identify the core issue for each person (hopefully).

**Comment by madbuda** [comment]
I found setting a static IP resolved this for me

**Comment by clorigo** [comment]
I added this plugin after 3.2.8 was released after installing BOND recently (June 2021) - I configured using Hombridge-UX and am using a static IP address for the BOND device.  

Without looking at the source it looks to me like the code expects an object result from parsing the JSON but it is not created (therefore "NULL")  

Will be glad to help in debugging.

**Comment by jjw867** [comment]
I was having this same problem on a new Homebridge installation.  The new installation is on a Raspbian RPI4.  The old installation, still running, is in a AMD64 container.  The containerized version works, the Raspbian uncontainerized version does not.  The bond is at a static IP.

Raspbian:

Node.js Version:  v14.17.1
Npm Version:  v6.14.8

AMD64 container:

Node.js Version:  v14.17.0
Npm Version:  v6.14.13

Raspbian error output:

[6/18/2021, 3:33:44 PM] [Bond] A request error occurred: undefined
[6/18/2021, 3:33:44 PM] [Bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
[6/18/2021, 3:33:44 PM] [Bond] A request error occurred: undefined
[6/18/2021, 3:33:44 PM] [Bond] Error getting version: TypeError: Cannot read property 'bondid' of undefined
[6/18/2021, 3:33:44 PM] [Bond] 0 cached accessories were loaded
(node:3780) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bondid' of undefined
    at BondPlatform.getDevices (/usr/local/lib/node_modules/homebridge-bond/dist/platform.js:47:65)
    at /usr/local/lib/node_modules/homebridge-bond/dist/platform.js:39:26
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/homebridge-bond/dist/platform.js:38:28
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:3780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:3780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

I may have found the fix.  When I added the module and filled out the form given with the JSON was different than what I had on the AMD64.  This was the JSON blob from when I filled out the form on the Raspbian:

{
            "bonds": [
                {
                    "ip_address": "192.168.1.39",
                    "token": "<redacted>"
                }
            ],
            "include_dimmer": false,
            "include_toggle_state": false,
            "fan_speed_values": false,
            "platform": "Bond"
        }

JSON Blob that worked on AMD64:

{
            "platform": "Bond",
            "bonds": [
                {
                    "ip_address": "192.168.1.39",
                    "token": "<redacted>"
                }
            ]
        }

**Comment by tylervsd** [comment]
I had this same error and was able to resolve. In my situation, it turns out the IP address of my ceiling fan changed, and this change was not reflected in the Bond app. I had to get the new IP from my wirelesss router.

To verify the fan IP address is valid, I used the following curl:
`curl -H "BOND-Token: ABCXYZ" -i http://192.168.0.8/v2/devices`

Expectation is that this command returns some json.

**Comment by dhpeter** [comment]
I updated everything this morning, seems to be running well. Thanks!
