### ISSUE TITLE
Crash "cannot read property 'power' of undefined"

### ISSUE THREAD

**Issue by dxdc** [aarons22/homebridge-bond#153]
**Describe the bug**
Periodic crashes (every few days) cause HB restarts.

```
[5/4/2021, 8:42:11 AM] [Bond] A request error occurred: undefined
TypeError: Cannot read property 'power' of undefined
    at GenericAccessory.updateState (/usr/lib/node_modules/homebridge-bond/dist/accessories/GenericAccessory.js:22:49)
    at /usr/lib/node_modules/homebridge-bond/dist/accessories/GenericAccessory.js:32:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
TypeError: Cannot read property 'power' of undefined
    at GenericAccessory.updateState (/usr/lib/node_modules/homebridge-bond/dist/accessories/GenericAccessory.js:22:49)
    at /usr/lib/node_modules/homebridge-bond/dist/accessories/GenericAccessory.js:32:18
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
abort(TypeError: Cannot read property 'power' of undefined). Build with -s ASSERTIONS=1 for more info.
```

**Information (please complete the following information):**
 - Plugin version homebridge-bond@3.2.8
 - Bond firmware version v2.17.4.2-beta
 - How homebridge is run: pm2
 
 I also see these kinds of errors. Not sure if it's just a network issue / timeout.
 
 ```
 homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:[4/18/2021, 12:56:53 AM] TypeError: Cannot read property 'bondid' of undefined
homebridge-error__2021-04-18_04-37-10.log:TypeError: Cannot read property 'bondid' of undefined
```

**Comment by searls** [comment]
I think I'm seeing the same thing. Just installed for the first time via HOOBS:

```
5/4/2021, 1:07:27 PM [Bond] Initializing Bond platform...
5/4/2021, 1:07:28 PM [Bond] 0 cached accessories were loaded
5/4/2021, 1:07:28 PM [Bond] Getting devices for this Bond (ZZDI37039)...
5/4/2021, 1:07:28 PM [Bond] 2 devices were found on this Bond (ZZDI37039).
5/4/2021, 1:07:28 PM [Bond] Attempting to add 2 devices that were not previously added.
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] A request error occurred: undefined
5/4/2021, 1:07:38 PM [Bond] [Master Bedroom Fan Remote] actions: TurnOff,SetSpeed,SetDirection,ToggleLight,StartIncreasingBrightness,StartDecreasingBrightness,OEMTimer,OEMRandom,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed,ToggleDirection,TurnLightOn,TurnLightOff
5/4/2021, 1:07:38 PM [Bond] Error getting devices: TypeError: Cannot read property 'action' of undefined
```

**Comment by searls** [comment]
Just pulled down the plugin and ran it locally against a fresh copy of homebridge (macOS, node 14) and couldn't replicate the problem against the same bridge

**Comment by searls** [comment]
Tried installing a fresh raspberry pi / homebridge image and set up homebridge UI and seeing similar errors:

```
[04/05/2021, 22:09:37] [Bond] Configuring Accessory: My Room Master Bedroom Fan Remote
[04/05/2021, 22:09:37] [Bond] [Master Bedroom Fan Remote] actions: TurnOff,SetSpeed,SetDirection,ToggleLight,StartIncreasingBrightness,StartDecreasingBrightness,OEMTimer,OEMRandom,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed,ToggleDirection,TurnLightOn,TurnLightOff
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] A request error occurred: undefined
[04/05/2021, 22:09:47] [Bond] [Balcony Ceiling Fan Remote] actions: TurnOff,SetSpeed,SetDirection,ToggleLight,StartIncreasingBrightness,StartDecreasingBrightness,OEMTimer,OEMRandom,Stop,TogglePower,TurnOn,IncreaseSpeed,DecreaseSpeed,ToggleDirection,TurnLightOn,TurnLightOff
[04/05/2021, 22:09:47] [Bond] Error getting devices: TypeError: Cannot read property 'action' of undefined
```

**Comment by searls** [comment]
Weirdly, i've narrowed it down to the plugin working fine when homebridge is in debug mode, but failing (as shown above) when not in debug mode

**Comment by searls** [comment]
Just saw the error again, but this time it did trigger during debug mode so I could see the failed request:

```
[05/05/2021, 10:16:11] [Bond] A request error occurred: undefined
[05/05/2021, 10:16:11] [Bond] Error (185e4f38ad364002) [get http://192.168.1.229/v2/devices/11a547e8/commands/47e5f218] - {"message":"timeout of 10000ms exceeded","name":"Error","stack":"Error: timeout of 10000ms exceeded\n    at createError (/usr/local/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at RedirectableRequest.handleRequestTimeout (/usr/local/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:280:16)\n    at RedirectableRequest.emit (events.js:315:20)\n    at Timeout._onTimeout (/usr/local/lib/node_modules/homebridge-bond/node_modules/follow-redirects/index.js:170:12)\n    at listOnTimeout (internal/timers.js:554:17)\n    at processTimers (internal/timers.js:497:7)","config":{"url":"http://192.168.1.229/v2/devices/11a547e8/commands/47e5f218","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"615064ede36920b7","Bond-UUID":"185e4f38ad364002","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.21.1","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":10000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"axios-retry":{"retryCount":0,"lastRequestTime":1620224160997}},"code":"ECONNABORTED"}
```

New devices are failing to be added and picked up as a result, but existing devices continue to work

**Comment by searls** [comment]
There seems to be an underlying issue with the request, as increasing the timeout to 30s didn't fix it

**Comment by aarons22** [comment]
@searls what bond firmware are you running? @dxdc reported this on a beta firmware, so I'm wondering if there is something going on there.

The changes from 3.2.6 and 3.2.8 only affected the fireplace accessory, so if it was running smoothly before on 3.2.6 (released on march 31), then I'm _guessing_ it's related to bond firmware and the API potentially changing?

**Comment by searls** [comment]
I'm on Bond Bridge v2.17.4-1-g29bc8b4

**Comment by aarons22** [comment]
Thanks @searls . I'm adding better logging for network failures in the upcoming release. 

@dxdc out of curiosity, is your Bond using a static IP?

**Comment by JeffGoldner** [comment]
I'm seeing pretty much the same problem. It had been working yesterday when I got my new Bond Bridge. But I had to remove and re-add a fan that was not working in the Bond app. Got that sorted out, restarted the plug in and it errors out - sometimes with no devices recognized, sometimes one or two out of four.

I turned on Homebridge debug mode and everything is working now.

Same firmware v2.17.4-1-g29bc8b4. Reserved IP address although it has not changed after many reboots of the Bond so that wasn't the problem.
