### ISSUE TITLE
Accessories not feeding through to HomeKit

### ISSUE THREAD

**Issue by chanelt99** [aarons22/homebridge-bond#162]
**Describe the bug**
Can successfully add Bond bridge to HomeKit using QR code however accessories associated with the Bond bridge in question are not appearing in HomeKit, issue presented after RaspberryPi lost power. 
Troubleshooting completed:
- Accessories are present and responsive via Bond iOS App
- Restarted Homebridge
- Uninstalled and reinstalled plug-in multiple times
- Confirmed IP address and token are correct
- Removed all cached accessories

**Information:**
 - Plugin version : v3.2.8
 - Bond firmware version: v2.17.4-1-g29bc8b4
 - How homebridge is run: Homebridge UI
 
**Logs**
[28/06/2021, 5:26:03 pm] [Homebridge UI] Homebridge restart request received
[28/06/2021, 5:26:03 pm] [Homebridge UI] UI / Bridge settings have not changed; only restarting Homebridge process
[28/06/2021, 5:26:03 pm] [Homebridge UI] Sending SIGTERM to Homebridge
[28/06/2021, 5:26:03 pm] Got SIGTERM, shutting down Homebridge...
[28/06/2021, 5:26:03 pm] Got SIGTERM, shutting down child bridge process...
[28/06/2021, 5:26:08 pm] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[28/06/2021, 5:26:13 pm] [HB Supervisor] Restarting Homebridge...
[28/06/2021, 5:26:13 pm] [HB Supervisor] Starting Homebridge with extra flags: -I -D
[28/06/2021, 5:26:13 pm] [HB Supervisor] Started Homebridge v1.3.1 with PID: 28216
Initializing HAP-NodeJS v0.9.2...
[28/06/2021, 5:26:14 pm] Loaded config.json with 0 accessories and 2 platforms.
[28/06/2021, 5:26:14 pm] Loaded 0 cached accessories from cachedAccessories.
[28/06/2021, 5:26:14 pm] ---
[28/06/2021, 5:26:15 pm] Loaded plugin: homebridge-bond@3.2.8
[28/06/2021, 5:26:15 pm] Registering platform 'homebridge-bond.Bond'
[28/06/2021, 5:26:15 pm] ---
[28/06/2021, 5:26:15 pm] Loaded plugin: homebridge-config-ui-x@4.41.1
[28/06/2021, 5:26:15 pm] Registering platform 'homebridge-config-ui-x.config'
[28/06/2021, 5:26:15 pm] ---
[28/06/2021, 5:26:15 pm] Loading 2 platforms...
[28/06/2021, 5:26:15 pm] [Config] Initializing config platform...
[28/06/2021, 5:26:15 pm] [Config] Running in Service Mode
[28/06/2021, 5:26:15 pm] [Bond] Initializing Bond platform...
Preparing Advertiser for 'Homebridge 87DB FE9F' using bonjour-hap backend!
Setup Payload:
X-HM://0023TQTI11A29
Enter this code with your HomeKit app on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 215-20-601 │     
    └────────────┘     
                       
Starting to advertise 'Homebridge 87DB FE9F' using bonjour-hap backend!
[28/06/2021, 5:26:15 pm] Homebridge v1.3.1 (Homebridge 87DB) is running on port 51137.
Initializing HAP-NodeJS v0.9.2...
[28/06/2021, 5:26:16 pm] [homebridge-bond] Launched external bridge with PID 28240
[28/06/2021, 5:26:16 pm] Registering platform 'homebridge-bond.Bond'
[28/06/2021, 5:26:16 pm] [homebridge-bond] Loaded homebridge-bond v3.2.8 successfully
[28/06/2021, 5:26:16 pm] Loaded 0 cached accessories from cachedAccessories.0ECB67006EE0.
[28/06/2021, 5:26:16 pm] [homebridge-bond] Config: {
  "bonds": [
    {
      "ip_address": "192.168.1.102",
      "token": "4fb478080eb7533a"
    }
  ],
  "include_dimmer": false,
  "include_toggle_state": true,
  "fan_speed_values": true,
  "platform": "Bond"
}
Preparing Advertiser for 'homebridge-bond A139' using bonjour-hap backend!
[28/06/2021, 5:26:16 pm] [homebridge-bond] Request (185e9460bf620000) [get http://192.168.1.102/v2/devices]
[28/06/2021, 5:26:16 pm] [homebridge-bond] Request (185e9460bf638000) [get http://192.168.1.102/v2/sys/version]
Starting to advertise 'homebridge-bond A139' using bonjour-hap backend!
[28/06/2021, 5:26:17 pm] Homebridge v1.3.1 (homebridge-bond) is running on port 33418.
[28/06/2021, 5:26:17 pm] [homebridge-bond] Error (185e9460bf620000) [get http://192.168.1.102/v2/devices] - {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://192.168.1.102/v2/devices","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"4fb478080eb7533a","Bond-UUID":"185e9460bf620000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.21.1","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":10000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"axios-retry":{"retryCount":0,"lastRequestTime":1624865176975}}}
[28/06/2021, 5:26:17 pm] [homebridge-bond] Error (185e9460bf638000) [get http://192.168.1.102/v2/sys/version] - {"message":"Request failed with status code 404","name":"Error","stack":"Error: Request failed with status code 404\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:260:11)\n    at IncomingMessage.emit (events.js:327:22)\n    at endReadableNT (internal/streams/readable.js:1327:12)\n    at processTicksAndRejections (internal/process/task_queues.js:80:21)","config":{"url":"http://192.168.1.102/v2/sys/version","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"4fb478080eb7533a","Bond-UUID":"185e9460bf638000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.21.1","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":10000,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"maxBodyLength":-1,"axios-retry":{"retryCount":0,"lastRequestTime":1624865176976}}}
[28/06/2021, 5:26:17 pm] [homebridge-bond] 0 cached accessories were loaded
[28/06/2021, 5:26:17 pm] [homebridge-bond] A request error occurred: undefined
[28/06/2021, 5:26:17 pm] [homebridge-bond] Error getting device ids: TypeError: Cannot convert undefined or null to object
[28/06/2021, 5:26:17 pm] [homebridge-bond] A request error occurred: undefined
[28/06/2021, 5:26:17 pm] [homebridge-bond] Error getting version: TypeError: Cannot read property 'bondid' of undefined
(node:28240) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'bondid' of undefined
    at BondPlatform.getDevices (/usr/lib/node_modules/homebridge-bond/dist/platform.js:47:65)
    at /usr/lib/node_modules/homebridge-bond/dist/platform.js:39:26
    at Array.forEach (<anonymous>)
    at /usr/lib/node_modules/homebridge-bond/dist/platform.js:38:28
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:28240) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:28240) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by aarons22** [comment]
the 404 errors are odd to me if you have confirmed your IP address. I just updated the plugin with improved logging and validation, hopefully that tells us what's going on here.

**Comment by aarons22** [comment]
Closing this as stale because it does not have enough current detail to act on, and the Homebridge/Bond/plugin stack has changed significantly since it was opened. If this still reproduces on the latest homebridge-bond version, please open a new bug report with debug logs, plugin version, Bond firmware, Homebridge version, Node version, and the device actions shown by the plugin.
