### ISSUE TITLE
Homekit showing fans on when they are not. Is this a known issue or just me

### ISSUE THREAD

**Issue by mtcjmmy** [aarons22/homebridge-bond#2]

**Comment by mtcjmmy** [comment]
Any help would be greatly appreciated

**Comment by twentyNoise** [comment]
I have this issue as well.

**Comment by iRayanKhan** [comment]
Going to test it to make sure and see if I can find a fix. If the device is fully powered off eg: a switch, then I am pretty sure nothing can be done.

**Comment by iRayanKhan** [comment]
Hey @plainsane using your version it would crash and give me this error:
[2018-11-6 23:46:54] [Bond] 1 cached accessories were loaded
[2018-11-6 23:46:54] Homebridge is running on port 51826.
[2018-11-6 23:46:54] [homebridge-tplink-smarthome.TplinkSmarthome] New Device Online: [My Smart Plug] plug [8006428AA29F7C0F1E774A04D4AE0C411A1C79F6] 10.0.0.5 9999
[2018-11-6 23:46:54] [homebridge-tplink-smarthome.TplinkSmarthome] Adding: [My Smart Plug] plug [8006428AA29F7C0F1E774A04D4AE0C411A1C79F6]
[2018-11-6 23:46:55] [Bond] Configure Accessory: null Fan
/usr/local/lib/node_modules/homebridge-bond/dist/index.js:168
            reset.getCharacteristic(Characteristic.On)
                 ^

TypeError: Cannot read property 'getCharacteristic' of undefined
    at BondPlatform.setupObservers (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:168:18)
    at Timeout.setInterval [as _onTimeout] (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:87:26)
    at ontimeout (timers.js:469:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
any ideas?

**Comment by iRayanKhan** [comment]
Fixed #5

**Comment by aarons22** [comment]
Closing this as it is no longer applicable with v2 API.
