### ISSUE TITLE
TypeError: Cannot read property 'some' of undefined

### ISSUE THREAD

**Issue by fancypants66** [aarons22/homebridge-bond#25]
Excited to see updates being made to homebridge-bond!
unfortunately receiving the following error on load.

`[9/27/2019, 12:40:08 AM] [Bond] Configuring Accessory: null Fan
[9/27/2019, 12:40:08 AM] TypeError: Cannot read property 'some' of undefined
    at Object.CFhasFan (/usr/lib/node_modules/homebridge-bond/dist/interface/Device.js:20:31)
    at BondPlatform.setupObservers (/usr/lib/node_modules/homebridge-bond/dist/index.js:94:29)
    at BondPlatform.configureAccessory (/usr/lib/node_modules/homebridge-bond/dist/index.js:90:14)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:386:24)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
[9/27/2019, 12:40:08 AM] Got SIGTERM, shutting down Homebridge...
`

**Comment by aarons22** [comment]
I suspect this is a data migration issue. A couple of questions:

- Have you updated your Bond to the latest firmware?
- Can you run the command `cat ~/.homebridge/accessories/cachedAccessories | pbcopy` and paste the contents here?

I think I need to build a quick migration guide for users coming from the pre-2.0.0 plugin

**Comment by iRayanKhan** [comment]
I just removed the Accessories file and restarted HomeBridge, all other accessories stayed the same and the New V2 fans appeared.

**Comment by aarons22** [comment]
@iRayanKhan I created a migration guide with those steps. Can you validate? https://github.com/aarons22/homebridge-bond/wiki/Migrating-from-v1-to-v2

**Comment by vdotn** [comment]
> @iRayanKhan I created a migration guide with those steps. Can you validate? https://github.com/aarons22/homebridge-bond/wiki/Migrating-from-v1-to-v2

This resolves it for me. (I picked up a new V2 bond so I can keep participating!)

**Comment by iRayanKhan** [comment]
Can confirm that those are the steps, would be good to link to the ReadME to where you update from V1 to V2, to since I didn’t know you needed a new app, ‘till I saw that plugin.

**Comment by fancypants66** [comment]
Yep worked perfectly. Deleted v1 cachedAccessories and no issues on boot. Thank you and keep up the great work!

**Comment by aarons22** [comment]
Thanks for the feedback! I updated the README with the migration guide.
