### ISSUE TITLE
No Bond Response

### ISSUE THREAD

**Issue by cargueta001** [aarons22/homebridge-bond#29]
@aarons22 Thanks for the continued support on this.

I've updated to the most current version of the plugin and the icons are visible but have a ghost action. In other words, the buttons don't provide a response from Bond.

**Comment by aarons22** [comment]
- can you remove the bond plugin from your setup and see if the issue persists? I’d like to confirm it’s due to this plugin and not a larger issue with homebridge and iOS 13
- how many bond devices do you have? It could be an issue with a larger number (I only have two fans)

**Comment by vdotn** [comment]
@cargueta001 Are you using the homebridge docker container from oznu by any chance? I had this issue and spent a good 30 minutes, turned out it wasn’t updating the npm module correctly/completely.

**Comment by cargueta001** [comment]
@vdotn Yes I am using the docker container from onzu. What steps did you take to remedy this?

**Comment by cargueta001** [comment]
@aarons22 I've removed the plugin and isolated it as the only unresponsive one. I have two fans as well in my BOND app, which are responding normal within that app.

**Comment by vdotn** [comment]
I ended up removing all my entries from packages.json (other than the dummy) and adding an ‘npm install <package>‘ line into startup.sh for each of my packages that I use. Turned out it hadn’t updated any of my packages in quite a while!

**Comment by cargueta001** [comment]
@vdotn Thanks for the suggestions. I made the tough decision to remove my Home and re-add it knowing very well my changes and customizations would be lost. Prior to that I removed the Bond plugin, cleared the cache and persist folders, adjust my config file and started from scratch.

After an hour of making my Home app the way it use to be, I reinstalled the Bond plugin and sudo rebooted my Raspberry Pi and have access once again! My only question is that no matter what happens, the syncing between the Bond app, Home app, and physical remote control still don't match up at times.

@aarons22 Is there is way to ping or to pull/refresh the Bond states every so often? Or is that essentially compromised since using a physical remote will screw up the syncing anyways?

**Comment by zaackyb21** [comment]
Could this be related to moving from the Bond V2 plugin to this plugin? I had the same issue after that. I am getting a different issue now when trying to reload the plugin where only some of the fans are loading.

This is the error I see for one of the fans that is not coming in.

[9/28/2019, 8:15:01 PM] [Bond] Adding accessory Garage CF
Unhandled rejection TypeError: Cannot read property 'action' of undefined
    at device.commands.filter.cmd (/usr/local/lib/node_modules/homebridge-bond/dist/interface/Device.js:32:24)
    at Array.filter (<anonymous>)
    at Object.fanSpeeds (/usr/local/lib/node_modules/homebridge-bond/dist/interface/Device.js:30:14)
    at BondPlatform.getFanSpeedValue (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:249:40)
    at BondPlatform.setupFanObservers (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:174:14)
    at BondPlatform.setupObservers (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:95:18)
    at BondPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:70:14)
    at devices.forEach.device (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:44:26)
    at Array.forEach (<anonymous>)
    at bondApi.getDevices.then.devices (/usr/local/lib/node_modules/homebridge-bond/dist/index.js:43:25)
    at tryCatcher (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:517:31)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:574:18)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:699:18)
    at Promise._fulfill (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:643:18)
    at PromiseArray._resolve (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise_array.js:144:14)
    at Promise._settlePromise (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:579:26)
    at Promise._settlePromise0 (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:619:10)
    at Promise._settlePromises (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/promise.js:699:18)
    at _drainQueueStep (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/usr/local/lib/node_modules/homebridge-bond/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by zaackyb21** [comment]
I was able to get my latest issue fixed by removing the apostrophes from my fan names.

**Comment by vdotn** [comment]
@cargueta001 I was wondering this too ... assuming it can’t get the state from the remote, I had thought the V2 api would at least sync state in the bond app when api calls are made. It doesn’t seem to. Probably a deficiency in how they implemented their API or app. I don’t think it’s anything we could influence from the homebridge side.

**Comment by aarons22** [comment]
If you use the physical remotes, you’re Bond is going to get out of sync, and there isn’t anything you can do to prevent that. The plugin treats the Bond as the source of truth, so anytime HomeKit requests the latest values (using `on('get')`), it hits the Bond API. I’m guessing you were able to work around this previously using the reset switch when things got out of sync. 

In the Bond Home app, you can fix the state of the light but unfortunately not the fan (at least last I checked). I’m wondering if it makes sense to add an option in the config `includeResetSwitch` (default: false) for those who do still might need it.

**Comment by aarons22** [comment]
Can we consider this issue closed?
