### ISSUE TITLE
Multiple Bond Bridges

### ISSUE THREAD

**Issue by Fernyman79** [aarons22/homebridge-bond#30]
The ability to add two or more different bond bridge devices. On larger houses, a single bond isn't enough to cover all rooms.

**Comment by Fernyman79** [comment]
I have a 2nd unit I can send to you, if it helps!

**Comment by aarons22** [comment]
I was wondering if there was anyone using multiple bonds 😄

Does homebridge let you define multiple platforms in the config using the same plugin?

**Comment by iRayanKhan** [comment]
Why not just setup another instance of HomeBridge? I got 4 different HomeBridge instances and it works all good.

**Comment by vdotn** [comment]
@aarons22 I think the way most other plugins implement it is by letting you create multiple accessories per plugin. For example see the IFTTT plugin. 

The way I see it being implemented is your plugin would be agnostic to how many bonds there actually are, the user specifies IPs and tokens in the config, plugin exports all the devices from all the bonds and handles the translation of which bond to send the api call to.

@iRayanKhan that would work too but kinda hacky. It’s a good workaround in the meantime though for sure!

**Comment by aarons22** [comment]
@vdotn yeah that’s the approach I would take as well. I was just curious if you could define multiple instances of the Bond plugin in the config as an alternative

**Comment by Fernyman79** [comment]
I’ve tried defining two platforms, but homebridge didn’t like it. It even loads all accessories (including Bond’s) but it crashes a few seconds later.

**Comment by iRayanKhan** [comment]
I’ll try it later tonight, I only have one bond, wonder if I can add 2 of the same bonds at once. Unless someone has a bond I can try to add then remove.

**Comment by iRayanKhan** [comment]
Can you paste the log of when it crashes?

**Comment by Fernyman79** [comment]
> Can you paste the log of when it crashes?
> […](#)

I’ll setup another instance tonight and try to reproduce. When I did it to my main installation I had to delete /accessories and /persist, and then re-add all my accessories in order to make homebridge work again.

**Comment by Fernyman79** [comment]
My log:

`[9/28/2019, 3:51:23 PM] Loaded config.json with 0 accessories and 4 platforms.
[9/28/2019, 3:51:23 PM] ---
[9/28/2019, 3:51:24 PM] Loaded plugin: homebridge-bond
[9/28/2019, 3:51:24 PM] Registering platform 'homebridge-bond.Bond'
[9/28/2019, 3:51:24 PM] ---
[9/28/2019, 3:51:25 PM] Loaded plugin: homebridge-camera-ffmpeg
[9/28/2019, 3:51:25 PM] Registering platform 'homebridge-camera-ffmpeg.Camera-ffmpeg'
[9/28/2019, 3:51:25 PM] ---
[9/28/2019, 3:51:25 PM] Loaded plugin: homebridge-config-ui-x
[9/28/2019, 3:51:25 PM] Registering platform 'homebridge-config-ui-x.config'
[9/28/2019, 3:51:25 PM] ---
[9/28/2019, 3:51:26 PM] Loaded plugin: homebridge-nest
[9/28/2019, 3:51:26 PM] Registering platform 'homebridge-nest.Nest'
[9/28/2019, 3:51:26 PM] ---
[9/28/2019, 3:51:26 PM] Loaded plugin: homebridge-rachio-platform
homebridge API version: 2.4
[9/28/2019, 3:51:26 PM] Registering platform 'homebridge-rachio-platform.Rachio-Platform'
[9/28/2019, 3:51:26 PM] ---
[9/28/2019, 3:51:26 PM] Loading 4 platforms...
[9/28/2019, 3:51:26 PM] [Config] Initializing config platform...
[9/28/2019, 3:51:26 PM] [Config] Spawning homebridge-config-ui-x with PID 432
[9/28/2019, 3:51:26 PM] [Nest] Initializing Nest platform...
[9/28/2019, 3:51:26 PM] [Nest] Fetching Nest devices.
[9/28/2019, 3:51:26 PM] [Rachio Controller] Initializing Rachio-Platform platform...
[9/28/2019, 3:51:26 PM] [Rachio Controller] RachioPlatform Init
[9/28/2019, 3:51:26 PM] [Rachio Controller] Refreshing devices...
[9/28/2019, 3:51:26 PM] [Camera-ffmpeg] Initializing Camera-ffmpeg platform...
[9/28/2019, 3:51:26 PM] Loading 0 accessories...
Load homebridge-bond.Bond
[9/28/2019, 3:51:26 PM] [homebridge-bond.Bond] ERR: Bond platform not defined in config.json
[9/28/2019, 3:51:26 PM] [Rachio Controller] Configure Cached Accessory: Rachio Controller - Rachio
[9/28/2019, 3:51:26 PM] [Rachio Controller] Configure Cached Accessory: Zone 1
[9/28/2019, 3:51:26 PM] [Rachio Controller] Configure Cached Accessory: Zone 2
[9/28/2019, 3:51:26 PM] [Rachio Controller] Configure Cached Accessory: Zone 3
[9/28/2019, 3:51:26 PM] [homebridge-bond.Bond] ERR: Bond platform not defined in config.json
[9/28/2019, 3:51:26 PM] [homebridge-bond.Bond] ERR: Bond platform not defined in config.json
[9/28/2019, 3:51:26 PM] [homebridge-bond.Bond] ERR: Bond platform not defined in config.json
[9/28/2019, 3:51:26 PM] [homebridge-bond.Bond] ERR: Bond platform not defined in config.json
[9/28/2019, 3:51:26 PM] Error: Cannot add a bridged Accessory with the same UUID as another bridged Accessory: a27b84c6-16b2-4e04-a2d3-7a57c4978cfa
    at Bridge.Accessory.addBridgedAccessory (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:268:13)
    at Server._configCachedPlatformAccessories (/usr/lib/node_modules/homebridge/lib/server.js:396:18)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:93:8)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:999:10)
    at internal/main/run_main_module.js:17:11
[9/28/2019, 3:51:26 PM] [Rachio Controller] Rachio Webhook Server Listening on port 27546. Ensure that http://76.126.86.62:12453 is forwarding to this port.
[9/28/2019, 3:51:26 PM] Got SIGTERM, shutting down Homebridge...
[9/28/2019, 3:51:27 PM] [Rachio Controller] Failed to refresh devices. Error: getaddrinfo EAI_AGAIN api.rach.io [500] GET https://api.rach.io/1/public/person/info
    at Request._callback (/usr/lib/node_modules/homebridge-rachio-platform/node_modules/rachio/lib/datastore/DataStore.js:25:21)
    at self.callback (/usr/lib/node_modules/homebridge-rachio-platform/node_modules/rachio/node_modules/request/request.js:186:22)
    at Request.emit (events.js:209:13)
    at Request.onRequestError (/usr/lib/node_modules/homebridge-rachio-platform/node_modules/rachio/node_modules/request/request.js:878:8)
    at ClientRequest.emit (events.js:209:13)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:209:13)
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
[9/28/2019, 3:51:27 PM] [Nest] Could not authenticate with Nest (code EAI_AGAIN). Retrying in 15 second(s).
[9/28/2019, 3:51:30 PM] [Config] Homebridge Config UI X v4.6.1 is listening on :: port 8080
homebridge.service: Main process exited, code=exited, status=143/n/a
homebridge.service: Failed with result 'exit-code'.
`

**Comment by aarons22** [comment]
Interesting, thanks for posting. I honestly didn’t think it would work but I was hoping it would 😅

I’ll keep this open as a feature request!

**Comment by aarons22** [comment]
Just pushed out a new version ([2.3.0](https://github.com/aarons22/homebridge-bond/releases/tag/2.3.0)) with support for multiple Bonds!
