### ISSUE TITLE
TypeError: bondData.map is not a function

### ISSUE THREAD

**Issue by jman731** [aarons22/homebridge-bond#69]
I have a Raspberry Pi with a freshly install os.  I am able to run homebridge with other plugins.  I have installed the homebridge-bond plugin.  

Bond Firmware version: v2.10.21

My plug-in version is: /usr/lib
`-- homebridge-bond@2.5.4

I changed my config file to only the following:

{
        "bridge": {
                "name": "Homebridge",
                "username": "",
                "port": ,
                "pin": ""
        },
        "description": "bond",
        "platforms": [{
                "platform": "Bond",
                "debug": true,
                "include_dimmer": true,
                "bonds": {
                        "ip_address": "192.168.86.180",
                        "token": "adeba92825697960"
                }
        }]
}

-------
* bridge details removed.
-------

when I try to run homebridge, I get the following error

pi@raspberrypi:~ $ homebridge
[4/12/2020, 1:59:24 PM] Loaded config.json with 0 accessories and 1 platforms.
[4/12/2020, 1:59:24 PM] ---
[4/12/2020, 1:59:25 PM] Loaded plugin: homebridge-bond
[4/12/2020, 1:59:25 PM] Registering platform 'homebridge-bond.Bond'
[4/12/2020, 1:59:25 PM] ---
[4/12/2020, 1:59:26 PM] Loaded plugin: homebridge-zway
[4/12/2020, 1:59:26 PM] Registering accessory 'homebridge-zway.ZWayServer'
[4/12/2020, 1:59:26 PM] Registering platform 'homebridge-zway.ZWayServer'
[4/12/2020, 1:59:26 PM] ---
[4/12/2020, 1:59:26 PM] Loading 1 platforms...
[4/12/2020, 1:59:26 PM] [Bond] Initializing Bond platform...
[4/12/2020, 1:59:26 PM] TypeError: bondData.map is not a function
    at Function.objects (/usr/lib/node_modules/homebridge-bond/dist/interface/Bo                                                                                                                                                             nd.js:19:35)
    at new BondPlatform (/usr/lib/node_modules/homebridge-bond/dist/index.js:34:                                                                                                                                                             35)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:337                                                                                                                                                             :32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:90:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:59:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22                                                                                                                                                             )
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js                                                                                                                                                             :74:12)
    at internal/main/run_main_module.js:18:47
[4/12/2020, 1:59:26 PM] Got SIGTERM, shutting down Homebridge...

**Comment by aarons22** [comment]
You need square brackets around your bonds value:
```
{
	"bridge": {
		"name": "Homebridge",
		"username": "",
		"port": 0,
		"pin": ""
	},
	"description": "bond",
	"platforms": [{
		"platform": "Bond",
		"debug": true,
		"include_dimmer": true,
		"bonds": [{
			"ip_address": "192.168.86.180",
			"token": "adeba92825697960"
		}]
	}]
}
```
