### ISSUE TITLE
Stalling home bridge with undefined error

### ISSUE THREAD

**Issue by wagnerec** [aarons22/homebridge-bond#98]
**Describe the bug**
Stall's home bridge on status query and show in the log:
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] A request error occurred: undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[7/8/2020, 2:27:03 PM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
**Expected behavior**
no stalling the process resulting in all other accessories to be listed as unresponsive

**Screenshots**

**Information (please complete the following information):**

 - Plugin version (run `npm list -g homebridge-bond` in terminal)
v 6.13.4
 - Bond firmware version
v2.10.21
 - iOS version (if issue is related to Home app)

**Additional context**
Two RF controlled fans. Same model, both three speeds and dimmable light.

**Comment by wagnerec** [comment]
Plugin version is 2.7.4, misread the output of the command.

**Comment by aarons22** [comment]
Are you still having this issue? It looks like all requests to the bond are failing.

If you are still having issues, please provide logs with [debug mode](https://github.com/aarons22/homebridge-bond/wiki/Enabling-Debug-Mode) turned on.

**Comment by wagnerec** [comment]
Yes, I just restarted it with Debug and its working for now but usually takes a few days run time to start occurring.

**Comment by wagnerec** [comment]
Still getting the error. Here’s the Bond debug logs:


[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc484e0000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc484ec000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc484f4000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc485ac000) [get http://bd25373.local/v2/devices/00000003/state]
[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc485b4000) [get http://bd25373.local/v2/devices/00000003/state]
[9/2/2020, 7:50:36 AM] [Bond] Request (185d13fc485b8000) [get http://bd25373.local/v2/devices/00000003/state]
[9/2/2020, 7:50:57 AM] [Bond] Request (185d13fc5c624000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:50:57 AM] [Bond] Request (185d13fc5c62c000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:50:57 AM] [Bond] Request (185d13fc5c630000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:52:08 AM] [Bond] Request (185d13fca1c04000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:52:08 AM] [Bond] Request (185d13fca1c08000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:52:08 AM] [Bond] Request (185d13fca1c0c000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc5c624000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc5c624000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":3,"lastRequestTime":1599069113163}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc484ec000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc484ec000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":4,"lastRequestTime":1599069109128}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc485b8000) [get http://bd25373.local/v2/devices/00000003/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000003/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc485b8000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":4,"lastRequestTime":1599069114175}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'speed' of undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'speed' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc5c62c000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc5c62c000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":3,"lastRequestTime":1599069118309}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc485b4000) [get http://bd25373.local/v2/devices/00000003/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000003/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc485b4000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":4,"lastRequestTime":1599069119000}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc5c630000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc5c630000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":3,"lastRequestTime":1599069123323}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc484e0000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc484e0000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":5,"lastRequestTime":1599069125679}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'speed' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Response (185d13fca1c04000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 7:52:12 AM] [Bond] got value: 0
[9/2/2020, 7:52:12 AM] [Bond] Response (185d13fca1c08000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 7:52:12 AM] [Bond] got value: false
[9/2/2020, 7:52:12 AM] [Bond] Response (185d13fca1c0c000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 7:52:12 AM] [Bond] got value: false
[9/2/2020, 7:52:12 AM] [Bond] Response (185d13fca1c90000) [get http://bd25373.local/v2/devices/00000003/state] - {"power":0,"speed":2,"light":0,"_":"52111b3d"}
[9/2/2020, 7:52:12 AM] [Bond] got value: false
[9/2/2020, 7:52:12 AM] [Bond] Response (185d13fca1c94000) [get http://bd25373.local/v2/devices/00000003/state] - {"power":0,"speed":2,"light":0,"_":"52111b3d"}
[9/2/2020, 7:52:12 AM] [Bond] got value: false
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc484f4000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc484f4000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":5,"lastRequestTime":1599069131218}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[9/2/2020, 7:52:12 AM] [Bond] Error (185d13fc485ac000) [get http://bd25373.local/v2/devices/00000003/state] - {"message":"timeout of 1ms exceeded","name":"Error","stack":"Error: timeout of 1ms exceeded\n    at createError (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/core/createError.js:16:15)\n    at ClientRequest.handleRequestTimeout (/usr/lib/node_modules/homebridge-bond/node_modules/axios/lib/adapters/http.js:256:16)\n    at Object.onceWrapper (events.js:286:20)\n    at ClientRequest.emit (events.js:203:15)\n    at Socket.emitRequestTimeout (_http_client.js:662:40)\n    at Object.onceWrapper (events.js:286:20)\n    at Socket.emit (events.js:198:13)\n    at Socket._onTimeout (net.js:443:8)\n    at ontimeout (timers.js:436:11)\n    at tryOnTimeout (timers.js:300:5)\n    at listOnTimeout (timers.js:263:5)\n    at Timer.processTimers (timers.js:223:10)\n","config":{"url":"http://bd25373.local/v2/devices/00000003/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d13fc485ac000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":5,"lastRequestTime":1599069131540}},"code":"ECONNABORTED"}
[9/2/2020, 7:52:12 AM] [Bond] A request error occurred: undefined
[9/2/2020, 7:52:12 AM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[9/2/2020, 8:09:48 AM] [Bond] Request (185d1400ad534000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 8:09:48 AM] [Bond] Request (185d1400ad53c000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 8:09:48 AM] [Bond] Request (185d1400ad544000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 8:14:36 AM] [Bond] Error (185d1400ad544000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"getaddrinfo ENOTFOUND bd25373.local bd25373.local:80","name":"Error","stack":"Error: getaddrinfo ENOTFOUND bd25373.local bd25373.local:80\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d1400ad544000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":10,"lastRequestTime":1599070471540}},"code":"ENOTFOUND"}
[9/2/2020, 8:14:36 AM] [Bond] A request error occurred: undefined
[9/2/2020, 8:14:36 AM] [Bond] error getting value: TypeError: Cannot read property 'power' of undefined
[9/2/2020, 8:14:42 AM] [Bond] Error (185d1400ad53c000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"getaddrinfo ENOTFOUND bd25373.local bd25373.local:80","name":"Error","stack":"Error: getaddrinfo ENOTFOUND bd25373.local bd25373.local:80\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d1400ad53c000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":10,"lastRequestTime":1599070477481}},"code":"ENOTFOUND"}
[9/2/2020, 8:14:42 AM] [Bond] A request error occurred: undefined
[9/2/2020, 8:14:42 AM] [Bond] error getting value: TypeError: Cannot read property 'speed' of undefined
[9/2/2020, 8:14:43 AM] [Bond] Error (185d1400ad534000) [get http://bd25373.local/v2/devices/00000018/state] - {"message":"getaddrinfo ENOTFOUND bd25373.local bd25373.local:80","name":"Error","stack":"Error: getaddrinfo ENOTFOUND bd25373.local bd25373.local:80\n    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)\n","config":{"url":"http://bd25373.local/v2/devices/00000018/state","method":"get","data":"{}","headers":{"Accept":"application/json, text/plain, */*","BOND-Token":"5e727d6f16a05fff","Bond-UUID":"185d1400ad534000","Content-Type":"application/json;charset=utf-8","User-Agent":"axios/0.19.2","Content-Length":2},"transformRequest":[null],"transformResponse":[null],"timeout":1,"xsrfCookieName":"XSRF-TOKEN","xsrfHeaderName":"X-XSRF-TOKEN","maxContentLength":-1,"axios-retry":{"retryCount":10,"lastRequestTime":1599070478027}},"code":"ENOTFOUND"}
[9/2/2020, 8:14:43 AM] [Bond] A request error occurred: undefined
[9/2/2020, 8:14:43 AM] [Bond] error getting value: TypeError: Cannot read property 'light' of undefined
[9/2/2020, 9:20:34 AM] [Bond] Request (185d1410dfb38000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 9:20:34 AM] [Bond] Request (185d1410dfb44000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 9:20:34 AM] [Bond] Request (185d1410dfb48000) [get http://bd25373.local/v2/devices/00000018/state]
[9/2/2020, 9:20:41 AM] [Bond] Response (185d1410dfb44000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 9:20:41 AM] [Bond] got value: 0
[9/2/2020, 9:20:41 AM] [Bond] Response (185d1410dfb48000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 9:20:41 AM] [Bond] got value: false
[9/2/2020, 9:20:42 AM] [Bond] Response (185d1410dfb38000) [get http://bd25373.local/v2/devices/00000018/state] - {"power":0,"speed":2,"light":0,"_":"ef4f047d"}
[9/2/2020, 9:20:42 AM] [Bond] got value: false

**Comment by aarons22** [comment]
It looks like you are using the bondId for your bond config, which can lead to unexpected behavior. Check out the README for the latest instructions on how to setup with IP Address.
